name: Documentation CI

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material mkdocs-minify-plugin
    - name: Deploy
      run: |
        SSH_DIR="${HOME}/.ssh"
        GIT_REPO="git@github.com:sundowndev/livre-blanc-video.git"
        mkdir "${SSH_DIR}"
        ssh-keyscan -t rsa github.com > "${SSH_DIR}/known_hosts"
        echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > "${SSH_DIR}/id_rsa"
        chmod 400 "${SSH_DIR}/id_rsa"
        git remote set-url origin "${GIT_REPO}"
        git config user.name "${{ secrets.GITHUB_USER }}"
        git config user.email "${{ secrets.GITHUB_USER }}@users.noreply.github.com"
        mkdocs gh-deploy
